export { default as CobieneLogo } from "./webp/cobiene-logo.webp";
export { default as CobieneLogoLarge } from "./webp/cobiene-logo-large.webp";
export { default as Slider1 } from "./webp/group-3.webp";
export { default as Slider2 } from "./webp/banneresperanzafuturo.webp";
export { default as Slider3 } from "./webp/slider3.webp";
// export { default as Slider3 } from "./webp/apoyosection.webp";
export { default as ImgDefault } from "./webp/image-default.webp";
// export { default as BannerContact } from "./webp/banner-contact.webp";
export { default as BannerContact } from "./webp/contactnew.webp";
// export { default as BannerJace } from "./webp/banner-jace.webp";
// export { default as BannerJas } from "./webp/banner-jas.webp";
export { default as BannerJas } from "./webp/saludo2.webp";
// export { default as BannerJae } from "./webp/banner-jae.webp";
export { default as BannerJae } from "./webp/jae.webp";
export { default as BannerJace } from "./webp/administracioncasas.webp";
// export { default as BannerFossep } from "./webp/banner-fossep.webp";
export { default as BannerFossep } from "./webp/fossep.webp";
// export { default as BannerFovime } from "./webp/banner-fovime.webp";
export { default as BannerFovime } from "./webp/fotoFovime.webp";
// export { default as BannerAcmp } from "./webp/banner-acmp.webp";
export { default as BannerAcmp } from "./webp/ceremonia2.webp";
// export { default as BannerBce } from "./webp/banner-bce.webp";
// export { default as BannerCmsts } from "./webp/banner-cmsts.webp";
export { default as BannerCmsts } from "./webp/casados.webp";
export { default as BannerTramites } from "./webp/banner-tramites.webp";
export { default as Convenios } from "./webp/catalogo.webp";
export { default as BannerDiscapacitado } from "./webp/apoyosad-1.webp";
// export { default as BannerApoyoEconomico } from "./webp/apoyoeconomico.webp";
export { default as BannerApoyoEconomico } from "./webp/saludo.webp";
export { default as BannerApoyoEducativo } from "./webp/newsaed.webp";
export { default as SliderNew } from "./webp/general.webp";
export { default as BannerBce } from "./webp/bazarnew.webp";
export { default as Playstore } from "./webp/getplaystore.webp";
export { default as AppStore } from "./webp/getappstore.webp";
export { default as Qr } from "./webp/codeqr.webp";
export * from "./webp/flip-book-images";
